kittencompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text= TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

kittencompanyblog/blog_posts/views.py
from flask import abort, render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from kittencompanyblog import db 
from kittencompanyblog.models import BlogPost
from kittencompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

#CREATE BLOGPOST
@blog_posts.route('/create', methods=["GET","POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        print("form validated")

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))
    else:
        print(form.errors)

    return render_template('create_post.html',form=form)


#VIEW BLOGPOST
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', 
                           title=blog_post.title,
                           date=blog_post.date,
                           post=blog_post
                           )



#UPDATE
@blog_posts.route('/<int:blog_post_id>/update', methods=["GET","POST"])
@login_required
def update(blog_post_id):
    #make sure author = current user:
    post = BlogPost.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        post.title = form.title.data 
        post.text = form.text.data
        post.user_id = current_user.id
        # commit to database (because it's an update):
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post_id))


    elif request.method == 'GET':    
        form.title.data = post.title
        form.text.data = post.text

    return render_template('create_post.html', title="Updating", form=form, post=post)


#DELETE
@blog_posts.route('/<int:blog_post_id>/delete', methods=["GET","POST"])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    
    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')

    return redirect(url_for('core.index'))

kittencompanyblog/core/views.py
from flask import render_template, request, Blueprint
from kittencompanyblog.users.views import users
from kittencompanyblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html',blog_posts=blog_posts, page=page)

@core.route('/info')
def info():
    return render_template('info.html', core=core, users=users)

kittencompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from kittencompanyblog import db #grabs db from __init__.py
from kittencompanyblog.models import User, BlogPost
from kittencompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from kittencompanyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

#register view
@users.route('/register', methods = ['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email = form.email.data,
                    username = form.username.data,
                    password = form.password.data)
        
        db.session.add(user)
        db.session.commit()
        flash("Thanks for registering!")
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


#login view
@users.route('/login', methods = ['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login successful")

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form = form)

#logout view
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

#show account (update user form page)
@users.route('/account', methods = ['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        #if uploaded picture data
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic 

        current_user.username = form.username.data 
        current_user.email = form.email.data 
        db.session.commit()
        flash("User account updated")
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email 

    profile_image = url_for('static', filename = 'profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image = profile_image, form=form)


#conect to and show all of user's blogposts (list)
@users.route('/<username>')
def user_posts(username):
    #grab blogpost associated to user
    page = request.args.get('page',1,type=int) #pagination
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blogpost.html', blog_posts=blog_posts, user=user)

kittencompanyblog/templates/account.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    <div align="center">
        <h1>Welcome to {{current_user.username}}'s page</h1>
        <img align="center" src="{{url_for('static', filename = 'profile_pics/'+current_user.profile_image)}}" alt="">

    </div>
</div>
 <div class="container">
<form method="POST" action="" enctype="multipart/form-data">

{{form.hidden_tag()}}
<div class="form-group">
    {{form.username.label(class="form-group")}}{{form.username(class="form-control")}}
</div>

<div class="form-group">
{{form.email.label(class="form-group")}}{{form.email(class="form-control")}}
</div>

<div class="form-group">
{{form.picture.label(class="form-group")}}{{form.picture(class="form-control")}} 
</div>

<div class="form-group">
    {{form.submit(class="btn btn-primary")}}
</div>



    </form>
 </div>
{% endblock %}

kittencompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitten Company Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</head>
<body>
    <ul class="nav">
        <li class="nav-link"><a href="{{url_for('core.index')}}">Home</a></li>
        <li class="nav-link"><a href="{{url_for('core.info')}}">Info</a></li>    
        {% if current_user.is_authenticated %}
        <li class="nav-link"><a href="{{url_for('users.logout')}}">Logout</a></li>
        <li class="nav-link"><a href="{{url_for('users.account')}}">Account</a></li>
        <li class="nav-link"><a href="{{url_for('blog_posts.create_post')}}">Create Post</a></li>
        {% else %}
        <li class="nav-link"><a href="{{url_for('users.login')}}">Login</a></li>
        <li class="nav-link"><a href="{{url_for('users.register')}}">Register</a></li>
        {% endif %}

    </ul>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

kittencompanyblog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">

<h1>{{ post.title }}</h1>
<h3>Written by: {{ post.author.username }}</h3>
<h5>Published on: {{post.date.strftime('%B %d, %Y')}}</h5>
<p>{{ post.text }}</p>

{% if post.author == current_user %}

<div>
    <a href="{{ url_for('blog_posts.update', blog_post_id = post.id) }}">Update</a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
</div>

{% endif %}

</div>

<div class="modal" tabindex="-1" id="del_modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

            <form action="{{url_for('blog_posts.delete_post', blog_post_id = post.id)}}">

                <input type="submit" value="Delete" class="btn btn-danger">
                
            </form>

         
        </div>
      </div>
    </div>
  </div>

{% endblock %}

kittencompanyblog/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="" class="form-group" method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label(class="form-control-label")}}
            {{form.title(class="form-control form-control-lg")}}
        </div>

        <div class="form-group">
            {{form.text.label(class="form-control-label")}}
            {{form.text(class="form-control form-control-lg")}}
        </div>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>

    </form>
</div>

{% endblock %}

kittencompanyblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron text-center">
    <h1>Kitten Company Blog</h1>
    <img src="{{url_for('static', filename = 'profile_pics/Hello.png')}}" alt="">
</div>

<div class="container">

{% for post in blog_posts.items %}

<div class="card">
    <div class="card-body">
        <h2><a class="card-title" href="{{ url_for('blog_posts.blog_post', blog_post_id = post.id) }}"></a>{{ post.title }}</h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written by: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y=%m-%d') }}</p>
        <a class="btn btn-primary" href="{{ url_for('blog_posts.blog_post', blog_post_id = post.id) }}">Read Blog Post</a>
    </div>
</div>

{% endfor %}

</div>


<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            
            {% if blog_posts.page == page_num %}
            <li class="class-item disabled">
                <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
            </li>

            {% else %}
            <li class="class-item">
                <a class="page-link" href="{{url_for('core.indexs', page=page_num)}}">{{ page_num }}</a>
            </li>

            {% endif %}
        {% endfor %}
        
  </nav>

{% endblock %}

kittencompanyblog/templates/info.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    <h1>Info about our Company</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
         Odit, tempora voluptas distinctio labore adipisci necessitatibus asperiores velit, 
         quia eveniet quod nulla dolores. Cum, neque consequatur deserunt nemo maxime facere quasi.</p>
</div>

{% endblock %}

kittencompanyblog/templates/login.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">

    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}} <br>
    {{form.password.label}}{{form.password}} <br>
    {{form.submit()}}

</form>

{% endblock %}

kittencompanyblog/templates/register.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">

    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}} <br>
    {{form.username.label}}{{form.username}} <br>
    {{form.password.label}}{{form.password}} <br>
    {{form.pass_confirm.label}}{{form.pass_confirm}} <br>
    {{form.submit()}}

</form>

{% endblock %}

kittencompanyblog/templates/user_blogpost.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="jumbotron text-align-center">
        <h1>Welcome to {{user.username}}'s page</h1>
        <img src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}" alt="">
    </div>


{% for post in blog_posts.items %}

<h2><a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>

Written by: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

<p class="text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
<br>
<p>{{post.text}}</p>
<br>
{% endfor %}
</div>

<!-- Paginator: -->

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            
            {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
                
                {% if blog_posts.page == page_num %}
                <li class="class-item disabled">
                    <a class="page-link" href="{{url_for('users.user_posts', username = user.username, page=page_num)}}">{{ page_num }}</a>
                </li>

                {% else %}
                <li class="class-item">
                    <a class="page-link" href="{{url_for('users.user_posts', username = user.username, page=page_num)}}">{{ page_num }}</a>
                </li>

                {% endif %}
            {% endfor %}
            
      </nav>


{% endblock %}